name: Build Next.js web
on: push
jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest
    steps:
    - name: Check code
      uses: actions/checkout@v3
      with:
          node-version: "16"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
    - name: Install NPM dependencies
      run: yarn install
    - name: Build project assets
      run: npm run build
  
